### ISSUE TITLE
Option to display Channel name instead of code

### ISSUE THREAD

**Issue by dlnorgaard** [usgs/vsc-valve#17]
For NOVAC gas data, the spectrometer serial # is often used as the channel, but this # if often meaningless to the user.  They have asked if another name can be assigned.  Far as I can tell, the channel name in the channels table does not seem to get used anywhere.  Is it possible to have an option to use this channel name (instead of code) in the channels list and plots?

**Comment by wtollett-usgs** [comment]
Are you envisioning this as a global option for a valve install or something like the 'Show All' checkbox in the Channel listbox?

**Comment by dlnorgaard** [comment]
I think it can go either way, but the latter might provide more flexibility.
