### ISSUE TITLE
Change Earthquake Depth Colors

### ISSUE THREAD

**Issue by wtollett-usgs** [usgs/vsc-valve#2]
By the way, there have been several requests to change the earthquake depth colors too.  Mainly the green color is hard to see against the gray DEM background.  Having other color options for the symbols and/or background would help.

**Comment by lantolik-usgs** [comment]
new processsing methods in earthquake locations at HVO may soon allow for negative depths, based on a fixed geoid.  Previously only positive depths were being computed.  Thus, this catalog change may suggest new extents (positive and negative) for the depth scale.

**Comment by wtollett-usgs** [comment]
Color change has been implemented, then changed to allow for 'old colors'.
